### ISSUE TITLE
engine

### ISSUE THREAD

**Issue by laripette** [lithander/MinimalChessEngine#4]
i saw your new leorik engine, you said it is the successor of your minimalchess engine.

does it mean that your minimalchess engine is abandoned ?

**Comment by lithander** [comment]
It's not abandoned! But the goal with MinimalChess was to make something minimal and simple to understand for a normal C# programmer. It already has a few features here and there where I felt conflicted because it made the engine better but not simpler. So Leorik is where I'm currently focusing on because I personally want to try new features and make a strong, competitive engine. But it can't be minimal and simple at the same time.

I still plan to release a version 1.0 for MinimalChess eventually. It's currently more or less feature complete but not perfectly tuned and polished. I'm still learning. ;)
